### ISSUE TITLE
如何安装插件 rbenv-gemset ？

### ISSUE THREAD

**Issue by LItterBoy-GB** [RubyMetric/rbenv-for-windows#36]
如何安装插件 rbenv-gemset ？
没有找到插件目录

**Comment by ccmywish** [comment]
你好，整个项目是用 `PowerShell` 写的，肯定不能安装用 `shell` 写的 `rbenv-gemset`，所以需要移植。

我没用过 `gemset`，现在用 `gemset` 的具体场景是什么？测试不同版本的 gem 吗？直接用 `Bundler` 能代替吗？

**Comment by LItterBoy-GB** [comment]
没事，刚开始没注意rbenv-gemset的具体内容，后面发现就是纯粹的shell。主要是为了对应上 rubymine的version manage。
